config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base

  validates :title, presence: true, length: { minimum: 5 }

  validates :text, presence: true, length: { minimum: 10 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end

  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end

  end

  def show
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h3>
            <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
          </h3>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>

    <p>
      <%= f.submit class: 'button' %>
    </p>

<% end %>

app/views/articles/edit.html.erb
<div id="page-container">
  <div class="grid-row">
    <div class="column-two-thirds">

      <h1>Article editor</h1>
      <%= render 'form' %>
      <%= link_to 'Back to list', articles_path %>

    </div>
    <div class="column-third">

    </div>
  </div>
</div>

app/views/articles/index.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
<% end %>

<div id="page-container">
  <div class="grid-row">
    <div class="column-two-thirds">

      <h1>Articles list</h1>
      <table>
        <tr>
          <th>Title</th>
          <th>Text</th>
        </tr>
        <% @articles.each do |article| %>
            <tr>
              <td><%= article.title %></td>
              <td><%= article.text %></td>
              <td><%= link_to 'Show', article_path(article) %></td>
              <td><%= link_to 'Edit', edit_article_path(article) %></td>
              <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
        <% end %>
      </table>

    </div>
    <div class="column-third">

      <h3>Additional actions</h3>
      <%= link_to 'New article', new_article_path %>

    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div id="page-container">
  <div class="grid-row">
    <div class="column-two-thirds">

      <h1>Article creator</h1>
      <%= render 'form' %>
      <%= link_to 'Back to list', articles_path %>

    </div>
    <div class="column-third">

    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div id="page-container">
  <div class="grid-row">
    <div class="column-two-thirds">

      <h1>Article details</h1>
      <p>
        <strong>Title:</strong>
        <%= @article.title %>
      </p>
      <p>
        <strong>Text:</strong>
        <%= @article.text %>
      </p>
      <%= link_to 'Back to list', articles_path %>

    </div>
    <div class="column-third">

      <h3>Additional actions</h3>
      <%= link_to 'Edit article', edit_article_path(@article) %>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<% content_for :head do %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
<% end %>

<%= render template: 'layouts/govuk_template' %>

app/views/welcome/index.html.erb
<h1>Welcome</h1>

<%= link_to 'Blog', controller: 'articles' %>